# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Konstantinos Psychas
email: github_username (at) gmail (dot) com
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Konstantinos Psychas
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kpsychas.github.io"

github_username:  kpsychas
quora_username:  Konstantinos-Psychas
stack_username:  kon-psych
stack_uid:   304623

# Build settings
markdown: kramdown
